name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        uses: dawidd6/action-setup-mingw@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          body: |
            Release ${{ github.event.inputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
