name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          curl -L -o mingw-w64.zip https://sourceforge.net/projects/mingw-w64/files/latest/download
          7z x -y mingw-w64.zip -oC:\mingw
          rm mingw-w64.zip
          echo 'C:\mingw\mingw64\bin' >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
