name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          curl -L -o msys2-base-x86_64.tar.xz https://github.com/msys2/msys2-installer/releases/latest/download/msys2-base-x86_64.tar.xz
          7z x -y msys2-base-x86_64.tar.xz -oC:\msys2
          C:\msys2\usr\bin\bash.exe -lc "echo -e '[mingw64]\nSigLevel = Optional TrustAll\nServer = https://mirrors.kernel.org/archlinux/$repo/os/$arch' >> /etc/pacman.conf"
          C:\msys2\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
          C:\msys2\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc"

      - name: Set up environment
        run: |
          echo 'C:\msys2\mingw64\bin' >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
