name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Set up MinGW
        run: |
          choco install -y mingw
          echo 'C:\tools\mingw64\bin' >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pacman --noconfirm -Sy mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
