name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          curl -L -o mingw-w64.zip https://mingw-w64.org/doku.php/_download/win-builds/win-builds-1.5.0.zip
          7z x -y mingw-w64.zip -oC:\mingw
          rm mingw-w64.zip
          echo 'C:\mingw\mingw64\bin' >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          body: |
            Release ${{ github.event.inputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
