name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          choco install -y msys2 --version=20210629.0.0
          echo 'C:\tools\msys64\mingw64\bin' >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
