name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          curl -L -o msys2installer.exe https://github.com/msys2/msys2-installer/releases/download/2021-11-23/msys2-x86_64-20211123.exe
          msys2installer.exe --quiet-mode --only-location --no-startmenu --disable-bash --skip-keybase --skip-terminfo --skip-npm --skip-autoupdate --root C:\mingw
          echo 'C:\mingw\mingw64\bin' >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
