name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          Invoke-WebRequest -Uri 'https://github.com/msys2/msys2-installer/releases/latest/download/msys2-base-x86_64-latest.tar.xz' -OutFile 'msys2-base-x86_64-latest.tar.xz'
          tar xf msys2-base-x86_64-latest.tar.xz
          mv msys64 C:\msys64
          C:\msys64\usr\bin\bash.exe --login -c "echo 'export PATH=/mingw64/bin:$PATH' >> ~/.bashrc"
          C:\msys64\usr\bin\bash.exe --login pacman --noconfirm -Sy mingw-w64-x86_64-gcc

      - name: Install dependencies
        run: |
          pacman --noconfirm -Sy mingw-w64-x86_64-gcc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc -o winchaos.exe main.c -lwindivert -lws2_32

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: winchaos
          path: winchaos.exe
